---
output:
  md_document:
    variant: gfm
---

# SDM Model Evaluation Tool User Guide for Developers

## Packages

The `sdm_tool()` Shiny App is created as an R package (sdmEvalToolUI) to
 simplify installation of dependencies and tracking package versions.

The sdmEvalToolCore contains database and file-related management tools which are used to support sdmEvalToolUI.

Therefore sdmEvalToolCore is a dependency of sdmEvalToolUI.

## Getting started

We use a standard [R package development workflow](https://r-pkgs.org/) which involves helper packages such as devtools and usethis.
Documentation is compiled with *roxygen2* (or `devtools::document()`), and we use *rcmdcheck* for package checks.

Install development dependencies:

```r
pak::pkg_install(c("devtools", "usethis", "rcmdcheck")) # Development deps
```

Clone repository if you haven't already:

```r
usethis::create_from_github("LandSciTech/sdmEvaluationTool")
```

Open the package (sdmEvalToolUI or sdmEvalTooCore) you want to work with and install any missing package dependencies:

```r
pak::local_install_dev_deps() # Package Deps
```

## Development Workflow

- Add/modify functions
- Use examples sections for development tests (see Documentation and Examples)
- Use `test_XXX()` functions to test Shiny Modules
- Use `sdm_tool()` to test the Shiny module overall
- Add tests
- Add/modify documentation
- Check and release the packages, see the steps in `RELEASE.R`

## Style

- The packages use broadly standard tidyverse-ish styling
  - snake-case names
  - generally `noun_verb()` or `category_description()` naming
  - Native R pipes (`|>`) and anonymous functions (`\(x)`)
  - `.data` and `.env` from rlang for NSE
  - tidyverse functions (dplyr, tidyr, purrr, rlang)
- Explicit function naming (shiny, bslib, and sdmEvalTool packages as exceptions)
- We use the [Air](https://posit-dev.github.io/air/) R formatter for linting
- [roxygen2 Rmarkdown documentation](https://roxygen2.r-lib.org/articles/rd-formatting.html)
  - E.g., `[function()]` to indicate functions and link to their docs

## Names and Organization

- Functions are grouped into different files by type
- `mod_` functions and files refer to modules
- `utils_` files refer to utility functions for different aspects of the app
- `test_` files and functions refer to those used for testing (including `utils_tests.R`)
- `sdmEvalToolXXX-package.R` and `zzz.R` files contain package settings
  - `sdmEvalToolXXX-package.R` contain imports and package-level documentation (if present)
  - `zzz.R` files contain Startup messages, startup options, and any global variables which need to be declared to avoid check NOTES.

## Documentation and Examples

- Document most functions, internal included.
  Most functions are exported, even if they would be normally marked as internal with `@noRd`.
  This allows cross referencing documentation with `[fun()]`.
- Use `@examplesIf have_data()` for examples which require local data.
- Use `@examplesIf interactive()` for examples which require an interactive session.

## Writing Functions

- Check args
  - If user feedback is required in Shiny functions, use `validate(need(x, msg)` to create sensible user messages.
  - If no feedback is required, but a function could be used in a Shiny contexts, use `req()` to check argument requirements.
- Try to keep functions modular for reuse and easier testing

## Config and core data sets

@psolymos, you may want to review/add to this

The config file (`sdmEvalToolCore/inst/config.yml`) comes from `spec/config.yml` - Defines component types - Expected file paths and naming - Expected displays for each component (used by the developer, not programmatic) - Expected data structure

This is used in `data-raw/DATASET.R` to create datasets in sdmEvalToolCore: - `components`: All available components, ids, names, paths, and general info - `tables`: Database tables - `fields`: Database fields by table and constraints - `default_questions` and `followup_questions`: Question templates if no questions provided - `user_roles`: User roles and permissions

These are re-built/created when following the steps in `RELEASE.R`

### Shiny App Organization

- `app.R` contains the main Shiny App with UI and Server logic as well as app-level options (theme, etc.)
- `mod_xxx.R` contain structural and utility modules
  - `mod_page_xxx.R` are structural modules for each page/tab in the app
  - `mod_comp_xxx.R` are structural modules for each component in the app (often, there is one component on one page, but occasionally there are two components on a page)
  - `mod_utils_xxx.R` are utility modules used throughout the app
- Each module usually has at least three unctions:
  - `test_xxx()`, `mod_xxx_ui()` (optional) and `mod_xxx_server()`
  - Optionally, a module may also have *module-specific* support functions used to create outputs, etc. General support functions will be found elsewhere.
- `test_xxx()` functions launch that module independently of the rest of the app with a collection of predefined materials (which can be changed).

Structural modules are nested: app > mod_page > mod_comp.
However, utility modules are used a different levels, and modify inputs/outputs/reactiveVals.

- Evaluations are provided by `mod_utils_evaluations` and are included in page-level modules.
- Components which use spatial *selections* also require `mod_utils_map_selections` in the component-level modules.
- Components which use maps view synchronization also require `mod_utils_map_sync` in the component-level modules

To best understand, explore the template modules: - Without spatial selections: `mod_page_template.R`, `mod_comp_template.R` - With spatial selections: `mod_page_template_spatial.R`, `mod_comp_template_spatial.R`

## Adding Components

### New Shiny Modules

- Decide if your change is a new component (`mod_comp_xxx.R`) on a *new* page (`mod_page_xxx.R`), or a new component added to an *existing* page.
- Decide if this is a species-level or model-level addition.
- Explore `mod_page_template.R` and `mod_page_template_spatial.R` for an overview of how to create new non-spatial and spatial (or at least partially spatial) pages.
- Explore `mod_comp_template.R` and `mod_comp_template_spatial.R` for an overview of how to create new non-spatial and spatial components.

Further examples

- `mod_page_model()` is a good page to use as a template for species-level components
- `mod_page_model_metadata()` is a good page to use as a template for model-level components
- Don't use the `mod_page_overview()` as a template, it's non-standard
- `mod_page_model()` is a good page to use as an example of multiple components in a single page
- `mod_page_observations()` is an example of a highly customized spatial component and page
- `mod_page_prediction()` is an example of a more basic spatial component and page

### New Data Processing

- Provided the new component materials are file types defined in `sdmEvalToolCore::read_file()`, `prep_materials()` should just work.
  Otherwise `read_file()` will need to be updated.
- New component types also need to be included in the `components` data frame, created from the specs in the sdmEvalToolCore package (`data-raw/DATASET.R`).
  Therefore new components should be added to the `spec/config.yml` and then the `components` data frame can be rebuilt (see `RELEASE.R`).

## Fiddly Notes

### Testing

- test/testthat/setup.R defines where the data (if any) is located from the perspective of test/testthat.
- If data cannot be found, `skip_if_no_data()` and `@examplesIf have_data()` prevent tests and data from running
- A basic list of inputs is defined in setup.R as well and used in many tests (`test_inputs`)

### Shiny Tests

- We've kept Shiny tests basic
- If you get an error "Shiny server returned 404 for values", use `shinytest2::record_test(app_to_test())` to get the error in the console terminal which is much easier to understand.
  (See https://github.com/rstudio/shinytest2/issues/356)
- Currently Shiny Tests only test that the app launches and expects data
- It uses JSON snapshot tests which will 'fail' if the local data example changes, so this might be a bit fragile.

### Pages/Components

- Pages include `span(title, class = "sdm-species-lvl")` or `sdm-model-lvl` to define a page as model- or species-level information (mostly this just colours the tab names).
- The observations component uses areas, but the observations processing is in points which are later converted to polygons

### Evaluations

- Only Spatial, Ordinal, and Yes/No questions can have follow ups
- Followups only show if the 'answer' to the parent questions is 'Affirmative' (see `affirmative()`)
- `affirmative()` needs to be updated if questions change, note this is especially the case for Spatial questions.
- Saving/Reloading evaluations (i.e. going from Shiny inputs, to evaluations list/df to JSON stored in data base, back to evaluations list/df and then back into Shiny inputs), can be fiddly, especially with the nested nature of the lists and R objects and with converting among formats.
  `test_data.R` contains several functions which create dummy data for testing these features.
  It can be tricky to ensure that these data sets match what is actually created by the Shiny app, however, so use caution.
- Currently ordinal values (i.e. One of "Extremely, "Moderately", "Slightly", etc.) are stored in a similar manner as spatial values (value = NA, subunits = "Extremely").
  This works, but doesn't make much sense so may change in future.

### Map Synchronization

Map synchronization is a bit of a tricky feature. It works by tracking the last 
modified map view (`view` zoom and center coords lat/lon) and updating other maps to match 
this view. It may seem a bit overly complicated, as we also track the currently 
active tab (`active_tab`) as well as the tab with the most updated map view (`set_by`).
Essentially these values are tracked to avoid infinitely triggering loops, to avoid flickering maps 
as they are constantly and minutely updated, and to avoid a weird issue where the 
recorded view of a map would change to nonsense values when switching away from that page.

Synchronization works by tracking the above values and storing them as `reactiveVals()` 
in a non-reactive list called `map_views`. Note that because views are tracked by the 
*page* name, this setup assumes only one map per page (otherwise, the most recently 
changed map on a page will be the one tracked... so this could work with multiple 
maps per page but it hasn't been tested). 
Map views are tracked by the map synchronizing utility module `mod_utils_map_sync.R`.
Whenever the view of a map on the *active* tab changes, that view is recorded in 
`map_views` under `view`, and we note the tab that triggered this update under 
`set_by` (the tab name passed along as `parent_id` from page module to component module). 
For example, if the view on the `predictions` tab changes *while that tab is active* 
(to avoid funny changes when leaving a tab), `map_views$view()` will be updated 
to that map view and `map_views$set_by()` will be updated to "predictions".

`active_tab` is set in the server part of `sdm_tool()` and tracks the active page/tab 
by name (matching values in the `sdm_tool()` argument, `tabs`).

The final part of the map synchronizing utility module `mod_utils_map_sync.R` is 
to update the map view on the current page. 

This only happens if:

- the `set_by` value is *not* the current page (avoid constantly triggering a 
  change in view if the user changes the view manually)
- the `active_tab` *is* the current tab (this may not be necessary, but ensures 
  that map views are only updated when the user has switched to that tab)
- the new map view is appreciably different from the current view (using the 
  `view_match()` utility function, this specifies a tolerance value under which 
  to ignore map view changes. This prevents constant fiddling map view changes 
  when flicking back and forth among pages).